[package]
name = "httpServer"
version = "0.1.0"
authors = ["segfo <k.segfo@gmail.com>"]

[dependencies]
serde = "1.0.10"
serde_json = "1.0"
serde_derive = "1.0.10"
router = "0.5.1"
hyper-native-tls = "0.2.4"
iron = "0.5.1"